server:
  port: 8083

spring:
  application:
    name: matching-engine
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: matching-engine-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

services:
  booking-service:
    url: http://localhost:8082/api/v1/rides

logging:
  level:
    com.ridepulse.matching: DEBUG
