services:
  # --------------------------------------------------
  # PostgreSQL: Primary Relational Database
  # --------------------------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: ridepulse-postgres
    environment:
      POSTGRES_USER: ridepulse_user
      POSTGRES_PASSWORD: ridepulse_password
      POSTGRES_DB: ridepulse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ridepulse-network

  # --------------------------------------------------
  # Redis: Ephemeral Geo-indexing, Locks, & Caching
  # --------------------------------------------------
  redis:
    image: redis:7.2-alpine
    container_name: ridepulse-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - ridepulse-network

  # --------------------------------------------------
  # Apache Kafka (KRaft Mode - No Zookeeper needed)
  # --------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: ridepulse-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - ridepulse-network

  # --------------------------------------------------
  # Kafka UI: Web Interface to Inspect Topics & Messages
  # --------------------------------------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ridepulse-kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - ridepulse-network

networks:
  ridepulse-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  kafka_data: