server:
  port: 8089

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ridepulse_db
    username: ridepulse_user
    password: ridepulse_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    com.ridepulse.payment: DEBUG
