server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        # Location Service REST & WebSocket
        - id: location-service-rest
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/locations/**
        - id: location-service-ws
          uri: ws://localhost:8084
          predicates:
            - Path=/ws-location/**

        # Booking Service
        - id: booking-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/rides/**

        # Notification Service WebSocket
        - id: notification-service-ws
          uri: ws://localhost:8086
          predicates:
            - Path=/ws-notifications/**

        # Dynamic Pricing (Python FastAPI)
        - id: pricing-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/pricing/**

        # User Service
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**

        # Driver Service
        - id: driver-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/drivers/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
